name: Slash Command Dispatch
on:
  issue_comment:
    # Type "edited" added here for test purposes. Where possible, avoid 
    # using to prevent processing unnecessary events.
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:

      # Advanced JSON configuration
      - name: Slash Command Dispatch (JSON)
        uses: peter-evans/slash-command-dispatch@v2
        id: scd
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          config: >
            [
              {
                "command": "rebase",
                "permission": "admin",
                "repository": "zsluedem/rchain-bench-test",
                "issue_type": "pull-request"
              },
              {
                "command": "help",
                "permission": "none",
                "issue_type": "issue",
                "repository": "zsluedem/rchain-bench-test"
              },
              {
                "command": "help",
                "permission": "none",
                "issue_type": "pull-request",
                "repository": "zsluedem/rchain-bench-test",
                "event_type_suffix": "-pr-command"
              },
              {
                "command": "help2",
                "permission": "none",
                "issue_type": "pull-request",
                "repository": "zsluedem/rchain-bench-test",
                "event_type_suffix": "-pr-command"
              },
              {
                "command": "help2",
                "permission": "none",
                "issue_type": "issue",
                "repository": "zsluedem/rchain-bench-test"
              },
              {
                "command": "example",
                "permission": "none",
                "issue_type": "issue",
                "repository": "zsluedem/rchain-bench-test"
              },
              {
                "command": "hello-world",
                "permission": "none",
                "issue_type": "issue",
                "repository": "zsluedem/rchain-bench-test"
              },
              {
                "command": "hello-world",
                "permission": "none",
                "issue_type": "pull-request",
                "repository": "zsluedem/rchain-bench-test",
                "event_type_suffix": "-pr-command"
              },
              {
                "command": "hello-workflow",
                "permission": "none",
                "issue_type": "issue",
                "repository": "zsluedem/rchain-bench-test",
                "static_args": [
                  "repository=${{ github.repository }}",
                  "comment-id=${{ github.event.comment.id }}",
                  "issue-number=${{ github.event.issue.number }}",
                  "actor=${{ github.actor }}"
                ],
                "dispatch_type": "workflow"
              },
              {
                "command": "ping",
                "permission": "none",
                "issue_type": "issue",
                "repository": "zsluedem/rchain-bench-test"
              },
              {
                "command": "black",
                "permission": "none",
                "issue_type": "pull-request",
                "repository": "zsluedem/rchain-bench-test"
              },
              {
                "command": "reset-demo",
                "permission": "none",
                "issue_type": "pull-request",
                "repository": "zsluedem/rchain-bench-test"
              }
            ]

      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}

